#!/usr/bin/env bash

# SPDX-License-Identifier: AGPL-3.0-or-later

#    ----------------------------------------------------------------------
#    Copyright © 2024, 2025  Pellegrino Prevete
#
#    All rights reserved
#    ----------------------------------------------------------------------
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
        "env")")"
_lib="$( \
  realpath \
    "${_bin}/../lib")"
_crash_bash="${_lib}/libcrash-bash/crash-bash"
_libevm="${_lib}/libevm/libevm"
_sourced \
  "${_crash_bash}" 2>/dev/null || \
  source \
    "${_crash_bash}"
_sourced \
  "${_libevm}"

# shellcheck disable=SC2034
_global_variables() {
  call_date=""
  target_command=""
  target_key=""
  target_value=""
  currency_type=""
  currency_address=""
  networks_all=""
  rpc_selection=""
  explorer_selection=""
  retries_max=""
  command_args=()
  color=""
  quiet=""
}

_requirements() {
  _check_cmd \
    'libevm-requirements' \
    'libevm'
  libevm-requirements
  _check_cmd \
    'node-run'
  _check_cmd \
    "evm-chains-info"
  _check_cmd \
    "evm-chains-explorers"
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/${app_name}"
  echo \
    "${_dir}"
}

_balance_send() {
  local \
    _currency_type="${1}" \
    _currency_token="${2}" \
    _target_address="${3}" \
    _target_amount="${4}" \
    _lib \
    _msg=()
  _lib="$( \
    _get_lib)/evm-wallet"
  _cmd=""
  if [[ "${_currency_type}" == "gas" ]]; then
    _cmd="${_lib}/balance-send"
    _args+=(
      "${quiet}"
      "${_wallet_seed}"
      "${_target_address}"
      "${_target_amount}"
      "${_network_backend}"
      "${_api_key_path}"
    )
  elif [[ "${_currency_type}" == "erc20" ]]; then
    _cmd="${_lib}/token-send"
    _args+=(
      "${quiet}"
      "${retries_max}"
      "${call_timeout}"
      "${wallet_seed}"
      "${api_key_path}"
      "${token_bytecode_path}"
      "${token_compiler_output_path}"
      "${measure_unit}"
      "${receipt_file_path}"
      "${target_address}"
      "${target_amount}"
    )
  fi
  _msg=(
    "Running send program"
    "'${_balance_send_cmd}'"
    "with options '${_balance_send_opts[*]}'."
  _msg_info \
    "${_msg[*]}"
}

_wallet_key_cmd() {
  local \
    _key="${1}" \
    _command="${2}" \
    _lib
  _lib="$( \
    _get_lib)/evm-wallet"
  echo \
    "${_lib}/${_key}-${_command}"
}

_key_get() {
  local \
    _key="${1}"
  if [[ "${_key}" == "address" ]] || \
     [[ "${_key}" == "balance" ]]; then
    _cmd="$( \
      "_wallet_key_cmd" \
        "${_key}" \
        "get")"
    _args+=(
      "${quiet}"
      "${_wallet_seed}"
      "${_network_backend}"
      "${_api_key_path}"
    )
  elif [[ "${_key}" == "seed" ]]; then
    cat \
      "${_wallet_seed}"
    exit \
      0
  elif [[ "${_key}" == "name" ]]; then
    echo \
      "${wallet_name}"
    return \
      0
  fi
}

_evm_wallet() {
  local \
    _target_command="${1}" \
    _wallet_path="${2}" \
    _wallet_password="${3}" \
    _wallet_seed="${4}" \
    _network="${5}" \
    _networks_all="${6}" \
    _rpc_selection="${7}" \
    _api_key_path="${8}" \
    _retries_max="${9}" \
    _currency_type="${10}" \
    _currency_address="${11}" \
    _target_key="${12}" \
    _target_value="${13}" \
    _command_args=() \
    _msg=() \
    _cmd \
    _args=() \
    _network_backend \
    _node_run_opts=() \
    _approve_call_opts=()
  shift \
    13
  _command_args+=(
    "$@"
  )
  _node_run_opts+=(
    -r
      "${_retries_max}"
  )
  _rpc_backend_get \
    "${_network}" \
    "${_rpc_selection}"
  if [[ "${_target_command}" == "get" ]]; then
    "_key_${_target_command}" \
      "${_target_key}"
    if [[ "${_target_key}" == "name" ]]; then
      return \
        0
    fi
  elif [[ "${_target_command}" == "send" ]]; then
    _target_address="${_target_key}"
    _target_amount="${_target_value}"
    _balance_send \
      "${_currency_type}" \
      "${currency_token}" \
      "${_target_address}" \
      "${_target_amount}"
  elif [[ "${_target_command}" == "approve" ]]; then
    # TODO: write approve function
    # _approve_call_opts_setup
    # evm-contract-call \
    #   "${_approve_call_opts[@]}" \
    #   "${}"
  else
    _msg=(
      "Unknown command '${_target_command}'."
    )
    _msg_error \
      "${_msg[*]}" \
      1
  fi
  node-run \
    "${_node_run_opts[@]}" \
    "${_cmd}" \
    "${_args[@]}"
}

_currency_type_auto_detect() {
  local \
    _currency_type
  _currency_type=""
  if [[ "${currency_address}" == "" ]]; then
    currency_type="gas"
  elif [[ "${currency_address}" == "" ]]; then
    currency_type="erc20"
  fi
  _set_override \
    "currency" \
    "type" \
    "${_currency_type}"
}

_set_overrides() {
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
  _set_override \
    "call" \
    "date" \
    "$(_get_date_human)"
  _set_override \
    "target" \
    "command" \
    "get"
  _set_override \
    "target" \
    "key" \
    "name"
  _set_override \
    "retries" \
    "max" \
    "300"
  _set_override \
    "networks" \
    "all" \
    "n"
  _set_override \
    "currency" \
    "address" \
    ""
  _currency_type_auto_detect
  _set_override \
    "rpc" \
    "selection" \
    "kirsh"
  _set_override \
    "explorer" \
    "selection" \
    "kirsh"
  _set_override \
    "target" \
    "network" \
    "100"
  _api_key_auto_detect \
    "${target_network}" \
    "${explorer_selection}"
  _wallet_overrides_set \
    "evm-wallet" \
    "default" \
    "y"
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true

EVM network wallet

Usage:
  ${app_name}
    [options]
    <command>
      (<command_args>)

  commands:
    get
      <wallet_name>
      <key>
    set
      <wallet_name>
      <key>
      <value>
    send
      <address>
      <amount>

  keys:
    address
    balance
    seed

  networks:
    all those supported by
    'evm-chains-info' as
    well as direct RPC addresses

  options:
     -R <rpc_selection>       RPC selection method.
                              Default: ${rpc_selection}
     -S <explorer_selection>  Network explorer selection method.
                              Default: ${explorer_selection}
     -r <retries_max>         Maximum number of retries before
                              failing.
                              Default: ${retries_max}

  send options:
     -t <currency_type>       Currency type.
                              It can be 'gas', 'erc20'.
     -C <currency>            Address of the ERC20
                              token on the network,
                              if type is 'erc20'.

  credentials options:
     -w <wallet_path>         Wallet path.
                              Default: ${wallet_path}
     -p <wallet_password>     Wallet password.
                              Default: ${wallet_password}
     -s <wallet_seed>         Wallet seed path.
                              Default: ${wallet_seed}
     -n <network>             EVM network name. Accepted values
                              are all those supported by
                              evm-chains-info and RPC addresses.
     -k <api_key>             Etherscan-like service key.
                              Default: ${api_key}

  libEVM options:
     -n <network>             EVM network name. Accepted values
                              are all those supported by
                              evm-chains-info and RPC addresses.

  application options:
     -h                       This message.
     -c                       Enable color output
     -v                       Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flags=(
      "${1}"
    ) \
    _flag
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  _msg_info "${app_name} configuration"
  _msg_info "                  Call date:   ${call_date}"
  _msg_info "             Target command:   ${target_command}"
  _msg_info "                 Target key:   ${target_key}"
  _msg_info "               Target value:   ${target_value}"
  _msg_info "               All networks:   ${networks_all}"
  _msg_info "       RPC selection method:   ${rpc_selection}"
  _msg_info "  Explorer selection method:   ${explorer_selection}"
  _msg_info "             Send options:"
  _msg_info "              Currency type:   ${currency_type}"
  _msg_info "           Currency address:   ${currency_address}"
  _msg_info "      Credentials options:"
  _msg_info "                Wallet path:   ${wallet_path}"
  _msg_info "            Wallet password:   ${wallet_password}"
  _msg_info "                Wallet seed:   ${wallet_seed}"
  _msg_info "                    API key:   ${api_key}"
  _msg_info "           LibEVM options:"
  _msg_info "             Target network:   ${target_network}"
  _msg_info "            Maximum retries:   ${retries_max}"
}

_globals
_global_variables
_requirements
_libevm_global_variables
_config_user_init \
  "${app_name}"
# shellcheck disable=SC2034
getopts_opts="$( \
  printf \
    "%s" \
    "S:E:a:r:" \
    "t:C:" \
    "$(_libevm_app_getopts_params_get)" \
    "n:" \
    "$(_wallet_getopts_params_get)" \
    "W:cvh")"
while \
  getopts \
    "${getopts_opts}" \
    arg; do
  _wallet_getopts_case
  _libevm_app_getopts_case
  case \
    "${arg}" in
    S) \
      override_rpc_selection="${OPTARG}" ;;
    E) \
      override_explorer_selection="${OPTARG}" ;;
    a) \
      override_networks_all="${OPTARG}" ;;
    r) \
      override_retries_max="${OPTARG}" ;;
    t) \
      override_currency_type="${OPTARG}" ;;
    C) \
      override_currency_address="${OPTARG}" ;;
    n) \
      override_target_network="${OPTARG}" ;;
    c) \
      override_color="y" ;;
    v) \
      override_quiet="n" ;;
    h) \
      _set_overrides && \
         _usage \
           0 ;;
    *) \
      if [[ " ${getopts_opts} " != *"${arg}"* ]]; then
        _msg_error \
          "Invalid argument '${arg}'." \
          0
        _usage \
          1
      fi ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( 0 < "$#" )); then
  target_command="${1}"
fi
if (( 1 < "$#" )); then
  wallet_name="${2}"
fi
if (( 2 < "$#" )); then
  target_key="${3}"
fi
if (( 3 < $# )); then
  target_value="${4}"
fi
shift \
  4 || \
  true
command_args+=(
  "$@"
)
_set_overrides
_show_config
app_opts=(
  "${target_command}"
  "${wallet_path}"
  "${wallet_password}"
  "${wallet_seed}"
  "${target_network}"
  "${networks_all}"
  "${rpc_selection}"
  "${api_key}"
  "${retries_max}"
  "${currency_type}"
  "${currency_address}"
  "${target_key}"
  "${target_value}"
)
_evm_wallet \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
