#!/usr/bin/env node

const _fs = require("fs");
const _path = require(
  'path');

function _dirname(
  _file_path) {
  _dir = _path.dirname(_file_path);
  return _dir 
}

function _file_exists(
  _path) {
  _return = false
  if (_fs.existsSync(
        _path)) {
  _return = true;
  }
  return _return;
}

function _file_read(
  _path) {
  return _fs.readFileSync(
    _path,
    {"encoding": "utf8",
     "flag": 'r'});
}

module.exports = {
  _dirname: _dirname,
  _file_exists: _file_exists,
  _file_read: _file_read,
};
