#!/usr/bin/env node

//
// SPDX-License-Identifier: AGPL-3.0-or-later
//

const { ethers } = require(
  "ethers");
_ethers = ethers;
_getDefaultProvider = _ethers.getDefaultProvider
const _libcrash = require(
  '../libcrash-js/crash-js');
_app_name_get = _libcrash._app_name_get;

function _global_variables() {
  target_network = '';
  api_key = '';
}

function _provider_get(
  _network,
  _api_key) {
  _provider_opts = {};
  if ( _network == "gnosis" ) {
    _rpc = "https://rpc.gnosischain.com" ;
    _default_network = _rpc;
  } 
  else if ( _network == "ethereum" ) {
    if ( _api_key != "" ) {
      _default_network = "etherscan";
      _provider_opts = {
        'etherscan': _api_key,
        'exclusive': [
          "etherscan",
          "infura"
        ]
      };
    }
    else {
      _rpc="https://rpc.ankr.com/eth"
      _default_network = _rpc;
    }
  }
  else {
    _default_network = _network;
  }
  _provider = _getDefaultProvider(
    _default_network,
    _provider_opts);
  _msg = "provider {_provider} generated".replace(
    "{_provider}",
    _provider);
  _msg_info(
    _msg);
  return _provider;
}

function _cmdline_parse() {
  target_network = "gnosis";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        target_network = _value;
      }
      if ( _index == 3 ) {
        api_key = _value;
      }
  });
}

module.exports = {
  _provider_get: _provider_get,
};

