#!/usr/bin/env node

const { ethers } = require(
  "ethers");
const _fs = require(
  'fs');
_path = require(
  'path');

function _global_variables() {
  wallet_path = "";
}

function _dirname(
  _file_path) {
  _dir = _path.dirname(_file_path);
  return _dir 
}

function _file_exists(
  _path) {
  _return = false
  if (_fs.existsSync(
        _path)) {
  _return = true;
  }
  return _return;
}

function _file_write(
  _path,
  _content) {
  _fs.writeFileSync(
    _path,
    _content);
}

function _log(
  _msg) {
  console.log(
    "INFO:",
    _msg);
}

function _mkseed(
  _path) {
  _wallet = ethers.Wallet.createRandom();
  _phrase = _wallet.mnemonic.phrase;
  if ( _path != "" ) {
    _dir = _dirname(
      _path);
    if ( _file_exists(_dir) != true ) {
      console.error(
        "ERROR: the directory",
        _dir,
        "does not exist");
      process.exit();
    }
    else {
      console.log(
        "INFO: writing to",
        _path);
    }
    _file_write(
      _path,
      _phrase);
    console.log(
      "INFO seed saved in",
      _path);
  }
  else {
    console.log(
    _phrase);
  }
}

function _cmdline_parse() {
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        wallet_path = _value;
      }
  });
  if ( wallet_path == "-h" ) {
    console.log(
      "Usage:");
    console.log(
      "  mkseed");
    console.log(
      "    (<path>)");
    process.exit();
  }
}

_global_variables();
_cmdline_parse();
_mkseed(
  wallet_path);

// console.log('wallet.address:', wallet.address)
// console.log('wallet.mnemonic.phrase:', wallet.mnemonic.phrase)
// console.log('wallet.privateKey:', wallet.privateKey)
