#!/usr/bin/env node

const 
  { ethers } =
    require(
      "ethers");
_ethers = 
  ethers;
_hd_wallet =
  _ethers.HDNodeWallet
const 
  _libcrash =
    require(
      '../libcrash-js/crash-js');
_app_name_get = 
  _libcrash._app_name_get;
_msg_info = 
  _libcrash._msg_info;
_msg_info_obj = 
  _libcrash._msg_info_obj;
_msg_error = 
  _libcrash._msg_error;
const 
  _fs_utils =
    require(
      '../libcrash-js/fs-utils');
_file_exists =
  _fs_utils._file_exists
_file_read =
  _fs_utils._file_read;


function _global_variables() {
  app_name =
    "wallet-get";
}


function _wallet_exists(
  _path) {
  let
    _exists,
    _template,
    _msg; 
  _exists =
    _file_exists(
      _path);
  if ( _exists == true ) {
    _template =
      "wallet '{_path}' already exists"
    _msg =
      _template.replaceAll(
        '{_path}',
      _path);
    _msg_error(
      _msg,
      "1");
  }
}


function
  _msg_info_seed_empty(
    _seed) {
  let
    _msg,
    _template;
  _template =
    "the seed '{_seed}' is empty."
  _msg =
    _template.replaceAll(
      "{_seed}",
      _seed);
  _msg_error(
    _msg,
    1)
}


function
  _seed_missing_error(
    _seed) {
  let
    _msg,
    _template;
  _template =
    "the seed '{_seed}' does not exist."
  _msg =
    _template.replaceAll(
      "{_seed}",
      _seed);
  _msg_error(
    _msg,
    1)
}


function _wallet_get(
  _path,
  _password,
  _seed,
  _provider) {
  let
    _password_show,
    _phrase,
    _phrase_show,
    _seed_exists;
  _password_show =
    "";
  if ( _password != "" ) {
    _password_show="****" 
  }
  _msg_info_obj(
    'wallet path',
    _path);
  _msg_info_obj(
    'wallet password',
    _password_show);
  _wallet_exists(
    _path);
  _phrase =
    "";
  if ( _seed != "" ) {
    _seed_exists =
      _file_exists(
        _seed);
    if ( _seed_exists == false ) {
      _seed_missing_error(
        _seed);
    }
    _msg_info_obj(
      'wallet seed',
      _seed);
    _phrase =
      _file_read(
        _seed); 
  }
  else if ( _seed == "" ) {
    _msg_info_seed_empty(
      _seed);
  }
  if ( _phrase != "" ) {
    _phrase_show="****" 
  }
  _msg_info_obj(
    'seed phrase',
    _phrase_show);
  _wallet =
    _node_wallet.fromPhrase(
      _phrase);
  _wallet.provider =
    _provider;
  _signer =
    _wallet.connect(
      _provider);
  return _signer;
}


_global_variables();


module.exports = {
  _wallet_get:
    _wallet_get
};
