#!/usr/bin/env node

const { ethers } = require("ethers");
_ethers = ethers;
const _path = require(
  'path');
const _network_provider = require('./network-provider');
const _fs_utils = require('./fs-utils');
const _wallet_get = require('./wallet-get');

function _global_variables() {
  app_opts = [];
  wallet_path = "";
  wallet_password = "";
  wallet_seed = "";
  target_network = "";
  api_key = "";
}

function _wallet_exists(
  _path) {
  if ( _fs_utils._file_exists(
         _path) == true ) {
    _msg = "ERROR: wallet '{_path}' already exists".replaceAll(
      '{_path}',
      _path);
    console.error(
      _msg);
    process.exit();
  }
}

async function _wallet_new(
  _path,
  _password,
  _seed,
  _network,
  _api_key) {
  _provider = _network_provider._provider_get(
    _network,
    _api_key);
  console.log(
    "INFO: path", _path);
  console.log(
    "INFO: password", _password);
  console.log(
    "INFO: seed", _seed);
  _wallet = _wallet_get._wallet_get(
    _path,
    _password,
    _seed,
    _provider);
}

function _overrides_set() {
  if ( target_network == "" ) {
    target_network = "gnosis";
  }
}

function _cmdline_parse() {
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        wallet_path = _value;
      }
      if ( _index == 3 ) {
        wallet_password = _value;
      }
      if ( _index == 4 ) {
        wallet_seed = _value;
      }
      if ( _index == 5 ) {
        target_network = _value;
      }
      if ( _index == 6 ) {
        api_key = _value;
      }
      // if ( 5 < _index ) {
      //   wallet_seed.push(
      //     _value);
      // }
  });
  if ( wallet_path == "" ) {
    console.error(
      "Usage: wallet-new <path> <password> <seed> <network> <api_key>");
    process.exit();
  }
}

_global_variables();
_cmdline_parse();
_overrides_set();
app_opts=[
  wallet_path,
  wallet_password,
  wallet_seed,
  target_network,
  api_key
];

// _wallet_new.apply(
//   null,
//   app_opts);

module.exports = {
  _wallet_new: _wallet_new
};
