#!/usr/bin/env node

const { ethers } = require(
  "ethers");
_ethers = ethers;
const _fs_utils = require(
  '../libcrash-js/fs-utils');
const _libcrash = require(
  '../libcrash-js/crash-js');
_msg_info = _libcrash._msg_info;
_msg_error = _libcrash._msg_error;

function _global_variables() {
  app_name = "wallet_get";
}

function _wallet_exists(
  _path) {
  if ( _fs_utils._file_exists(
         _path) == true ) {
    _msg = "wallet '{_path}' already exists".replaceAll(
      '{_path}',
      _path);
    _msg_error(
      _msg,
      "1");
  }
}

function _wallet_get(
  _path,
  _password,
  _seed,
  _provider) {
  _msg = "wallet path '{_path}'".replace(
    "{_path}",
    _path);
  _msg_info(
    _msg);
  _msg = "wallet password '{_password}'".replace(
    "{_password}",
    _password);
  _msg_info(
    _msg);
  _msg = "wallet seed '{_seed}'".replace(
    "{_seed}",
    _seed);
  _msg_info(
    _msg);
  _wallet_exists(
    _path);
  _phrase = _fs_utils._file_read(
    _seed); 
  _msg = "seed phrase: {_phrase}".replace(
    "{_phrase}",
    _phrase);
  _msg_info(
    _msg);
  _wallet = _ethers.HDNodeWallet.fromPhrase(
    _phrase,);
  _wallet.provider = _provider;
  _signer = _wallet.connect(
    _provider);
  return _signer;
}

app_name = "wallet-get"

module.exports = {
  _wallet_get: _wallet_get
};
