#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

//    ----------------------------------------------------------------------
//    Copyright © 2024, 2025  Pellegrino Prevete
//
//    All rights reserved
//    ----------------------------------------------------------------------
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.

const
  { ethers } =
    require(
      "ethers");
_ethers =
  ethers;
const
  _network_provider =
    require(
      './network-provider');
const
  _libcrash =
    require(
      '../libcrash-js/crash-js');
_msg_info = 
  _libcrash._msg_info;
_msg_info_obj = 
  _libcrash._msg_info_obj;
_msg_error = 
  _libcrash._msg_error;
const
  _wallet_get =
    require(
      './wallet-get');


function
  _global_variables() {
  app_name =
    "wallet-new";
  app_opts =
    [];
  wallet_path =
    "";
  wallet_password =
    "";
  wallet_seed =
    "";
  target_network =
    "";
  api_key =
    "";
  quiet =
    "";
}


function
  _seed_missing_error(
    _seed) {
  let
    _msg,
    _template;
  _template =
    "the seed '{_seed}' does not exist."
  _msg =
    _template.replaceAll(
      "{_seed}",
      _seed);
  _msg_error(
    _msg,
    1)
}


async function
  _wallet_new(
    _path,
    _password,
    _seed,
    _network,
    _api_key) {
  let
    _password_show,
    _provider;
  _provider =
    _network_provider._provider_get(
      _network,
      _api_key);
  _msg_info_obj(
    "wallet path",
    _path);
  _password_show =
    "";
  if ( _password != "" ) {
    _password_show =
      "****";
  }
  _msg_info_obj(
    "wallet password",
    _password_show);
  _msg_info_obj(
    "seed path",
    _seed);
  _wallet =
    _wallet_get._wallet_get(
      _path,
      _password,
      _seed,
      _provider);
}


function
  _overrides_set() {
  if ( target_network == "" ) {
    target_network =
      "gnosis";
  }
}


function
  _usage() {
  let
    _line,
    _text;
  _text = [
    "Usage:",
    "  wallet-new",
    "    <path>",
    "    <password>",
    "    <seed>",
    "    <network>",
    "    <api_key>",
    "    <quiet>"];
  for ( _line in _text ) {
    _msg_info(
      _line);
  }
  process.exit();
}


function
  _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        wallet_path =
          _value;
      }
      if ( _index == 3 ) {
        wallet_password =
          _value;
      }
      if ( _index == 4 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 5 ) {
        target_network =
          _value;
      }
      if ( _index == 6 ) {
        api_key =
          _value;
      }
      if ( _index == 6 ) {
        quiet =
          _value;
      }
  });
  if ( wallet_path == "" ) {
    _usage();
  }
}

_global_variables();

if ( require.main == module ) {
  _cmdline_parse();
  _overrides_set();
  app_opts=[
    wallet_path,
    wallet_password,
    wallet_seed,
    target_network,
    api_key,
    quiet
  ];
  _wallet_new.apply(
    null,
    app_opts);
}

module.exports = {
  _wallet_new:
    _wallet_new
};
