#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

const
  { ethers } =
    require(
      "ethers");
_ethers =
  ethers;
_wei_to_ether =
  _ethers.formatEther;
_parse_units =
  _ethers.parseUnits;

function
  _libcrash_require() {
  let
    _libcrash;
  try {
    _libcrash =
      require(
        "crash-js");
  } catch(
      _error) {
    try {
      _libcrash =
        require(
          "../libcrash-js/crash-js");
    } catch(
        _error) {
      _msg =
        "Install Crash Javascript.";
      throw _msg;
    }
  }
  return _libcrash
}

const
  _libcrash =
    _libcrash_require();
const
  _dirname =
    _libcrash._dirname;
const
  _file_read =
    _libcrash._file_read;
const
  _path_join =
    _libcrash._path_join;
const
  _msg_info =
    _libcrash._msg_info;
const
  _msg_info_obj =
    _libcrash._msg_info_obj;
const
  _msg_error =
    _libcrash._msg_error;
const
  _process_exit =
    _libcrash._process_exit;
const
  _wallet_get_module =
    require(
      './wallet-get');
const
  _wallet_get =
    _wallet_get_module._wallet_get;
const
  _balance_check_module =
    require(
      './balance-check');
const
  _balance_check =
    _balance_check_module._balance_check;
const
  _msg_error_balance_insufficient =
    _balance_check_module._msg_error_balance_insufficient
const
  _network_provider =
    require(
      './network-provider');
const
  _provider_get =
    _network_provider._provider_get;
const
  _msg_info_provider_generated =
    _network_provider._msg_info_provider_generated;

function
  _global_variables() {
  /* global
       app_name:
         writable */
  app_name =
    "balance-send";
  /* global
       app_opts:
         writable */
  app_opts =
    [];
  /* global
       method_args:
         writable */
  method_args =
    [];
  /* global
       wallet_seed:
         writable */
  wallet_seed =
    "";
  /* global
       target_address:
         writable */
  target_address =
    "";
  /* global
       target_amount:
         writable */
  target_amount =
    "";
  /* global
       target_network:
         writable */
  target_network =
    "";
  /* global
       api_key:
         writable */
  api_key =
    "";
  /* global
       measure_unit:
         writable */
  measure_unit =
    "";
  /* global
       quiet:
         writable */
  quiet =
    "";
}


function
  _ethers_to_wei(
    _amount) {
  return _parse_units(
    _amount,
    "ether");
}

function
  _send_msg_info(
    _target_amount,
    _amount,
    _measure_unit,
    _measure_unit_converted,
    _target_address) {
  let
    _msg;
  _msg =
    `Sending '${_target_amount}' '${_measure_unit}' `;
  if ( _measure_unit_converted != _measure_unit ) {
    _msg =
      _msg +
      `('${_amount}' ` +
      `'${_measure_unit_converted}') `;
  }
  _msg =
    _msg +
    `to address '${_target_address}'.`;
  _msg_info(
    _msg);
}

async function
  _balance_send(
    _wallet_seed,
    _target_address,
    _target_amount,
    _target_network,
    _api_key_path,
    _measure_unit) {
  let
    _amount,
    _balance_check_opts,
    _measure_unit_converted,
    _provider_get_opts,
    _send_opts;
  const
    _call_timeout =
      300000;
  if ( typeof(
         _measure_unit) === "undefined"  ||
         _measure_unit == "" ) {
    _measure_unit =
      "ether";
  }
  const
    _wallet_password =
      "";
  const
    _wallet_dir =
      _dirname(
        _wallet_seed);
  const
    _wallet_path_list = [
      _wallet_dir,
      "wallet.dat"
    ];
  const
    _wallet_path =
      _path_join(
        _wallet_path_list);
  _provider_get_opts = [
    _target_network
  ];
  if ( _api_key_path != "" ) {
    const
      _api_key =
        _file_read(
          _api_key_path);
    _provider_get_opts.push(
      _api_key);
  }
  const
    _provider =
      _provider_get.apply(
        null,
        _provider_get_opts);
  _msg_info_provider_generated(
    _provider);
  const
    _wallet_get_opts = [
      _wallet_path,
      _wallet_password,
      _wallet_seed,
      _provider
    ];
  const
    _wallet =
      _wallet_get.apply(
        null,
        _wallet_get_opts);
  const
    _sender_address =
      _wallet.address;
  _balance_check_opts = [
    _wallet_seed,
    _target_amount,
    _target_network,
    _api_key_path,
    _measure_unit
  ];
  _check =
    await _balance_check.apply(
      null,
      _balance_check_opts);
  if ( _check == false ) {
    _msg_error_balance_insufficient(
      _target_amount,
      _measure_unit);
  }
  _measure_unit_converted =
    _measure_unit;
  if ( _measure_unit == "wei" ) {
    _amount =
      _target_amount;
  }
  else if ( _measure_unit == "ether" ) {
    _amount =
      _ethers_to_wei(
        _target_amount);
    _measure_unit_converted =
      "wei";
  }
  _send_msg_info(
    _target_amount,
    _amount,
    _measure_unit,
    _measure_unit_converted,
    _target_address);
  _send_opts = {
    'to':
      _target_address,
    'value':
      _amount
  };
  const
    _tx =
      await _wallet.sendTransaction(
        _send_opts);
  console.log(
    _tx);
  const
    _receipt =
      await _tx.wait(
        1,
        _call_timeout);
  console.log(
    _receipt);
  return _receipt;
}

function
  _overrides_set() {
  if ( measure_unit == "" ) {
    measure_unit = "ether";
  }
}

function
  _config_show() {
  let
    _line;
  const
    _text = [
      `      Wallet seed: ${wallet_seed}`,
      `   Target address: ${target_address}`,
      `    Target amount: ${target_amount}`,
      `   Target network: ${target_network}`,
      `          API Key: ${api_key}`,
      `     Measure unit: ${measure_unit}`,
    ]
  for ( _line of _text ) {
    _msg_info(
      _line);
  }
}

function
  _usage() {
  let
    _line,
    _text;
  _text = [
    "Usage:",
    "  balance-send",
    "    <quiet>",
    "    <seed_path>",
    "    <target_address>",
    "    <amount>",
    "    (<target_network>)",
    "    (<api_key>)",
    "    (<measure_unit>)",
    "",
    "Args:",
    "  <seed_path>         Path on disk of the file",
    "                      containing the seed phrase.",
    "  <target_address>    Address to send some balance to.",
    "  <amount>            How much balance to send.",
    "  <target_network>    Name of the network to connect to.",
    "  <api_key>           Path on disk of the API key for",
    "                      the network service provider.",
    "                      Default: the wallet address.",
    "  <measure_unit>      Can be 'wei' or 'ether'.",
    "                      Default: 'ether'",
  ];
  for ( _line of _text ) {
    console.log(
      _line);
  }
  _process_exit();
}

function _cmdline_parse() {
  quiet =
    "y";
  process.argv.forEach(
    function (
      _value,
      _index,
      _array) {
      if ( _index == 2 ) {
        quiet =
          _value;
      }
      if ( _index == 3 ) {
        wallet_seed =
          _value;
      }
      if ( _index == 4 ) {
        target_address =
          _value;
      }
      if ( _index == 5 ) {
        target_amount =
          _value;
      }
      if ( _index == 6 ) {
        target_network =
          _value;
      }
      if ( _index == 7 ) {
        api_key =
          _value;
      }
      if ( _index == 8 ) {
        measure_unit =
        _value;
      }
  });
  if ( wallet_seed == "" ||
       target_address == "" ||
       target_amount == "") {
    _usage();
  }
}

if ( _cmdline_check(
       "balance-send") == true ) {
  _global_variables();
  _cmdline_parse();
  _config_show();
  app_opts = [
    wallet_seed,
    target_address,
    target_amount,
    target_network,
    api_key,
    measure_unit
  ];
  _balance_send.apply(
    null,
    app_opts);
}

module.exports = {
  _balance_send:
    _balance_send
};
